### ISSUE TITLE
In place of thumbnail image I wanted to pass title description and button for all

### ISSUE THREAD

**Issue by Amitshaale** [ericferreira1992/slider-carousel#1]
In place of thumbnail image how to pass content there is any option for passing it.

**Comment by ericferreira1992** [comment]
Hi @Amitshaale. Thanks by report a improve. Unfortunately it component was made to be that way. I'm will don't make this change, but feel free to do it, trough a forking from of the **slider-casousel** repository, so I can analisys the changes and maybe will approve it.

Waiting your contribution, thanks.
