### ISSUE TITLE
interrupts with input behavior

### ISSUE THREAD

**Issue by meoti** [ericferreira1992/slider-carousel#2]
For pages with slider-carousel component, weird enough integer input keeps  increasing on single click 
Do you have an idea what is causing this?

PS: am using angular 8
Thanks

**Comment by ericferreira1992** [comment]
Hi @meoti 
I'm don't undertand the problem you are having. Could you explain the problem better? If possible, send here some animated print or gif, so that I can better see the irregular behavior.
But, the component works well in Angular 8.

**Comment by meoti** [comment]
Thanks for the reply 

I made a screen recording for u 
When u use the spin-off in input of type number, it behaves as a long press.
This is only when carousel component is rendered.
At views where carousel is not rendered this behaviour is not seen.

Thanks for the component, saved a lot of time to write the same thing form scratch

**Comment by ericferreira1992** [comment]
Ah yes. I think understand now!
This "problem" really occurs, I had seen it a long time ago, but did has not time to fix. I believe that problem not going interfere in many things. The component really listen the click in full window, because it is necessary. But I will try fix it problem in soon.

Well, if you have more thing to say about the component, just say below.

Thanks, I wait for your reply.

**Comment by ericferreira1992** [comment]
Guy, can would you reply exactly it in the issue topic? Please :)
_____________________________________________________________________________
*Att,*
Eric A. Ferreira
*Ensino*: Graduado em *Engenharia da Computação (2015) * na *UEMG
Divinópolis*.
*Trabalho*: *Social Bank* www.socialbank.com.br (Mudando a forma como você
se relaciona com o dinheiro)
*.**Cargo*: Especialista em Sistemas | *Dev. FullStack**. *
"*Bem-aventurados os que não viram e creram.*" (João 20, 29)


Em qui, 3 de out de 2019 às 15:34, meoti <notifications@github.com>
escreveu:

**Comment by ericferreira1992** [comment]
@meoti
I just made the fix, run `npm update slider-carrousel` and post your result here, so that I can close this topic.
