### ISSUE TITLE
Photo urls that contain parentheses in the file name " ) or ( ", aren't loaded on slider, it gives unsafe style value url error

### ISSUE THREAD

**Issue by egzontina** [ericferreira1992/slider-carousel#27]
When image URLs have characters like "(" or ")". Images aren't loading on the slider and it displays the error " WARNING: sanitizing unsafe style value url", is it possible to fix this?

**Comment by ericferreira1992** [comment]
@egzontina do you can post a use example that problem?

**Comment by egzontina** [comment]
@ericferreira1992 for example this link: https://firebasestorage.googleapis.com/v0/b/example-5e68c.appspot.com/o/namewith(and).png?alt=media&token=5a2c80cd-5652-46c9-8a60-6dd8c2d542e5, the name of the file is: namewith(and).png.

**Comment by ericferreira1992** [comment]
@egzontina it's done! The version **1.1.0** of [slider-carousel](https://www.npmjs.com/package/slider-carousel) is available, and update to **Angular 10**. Thanks the report.
