### ISSUE TITLE
carousel disappear 

### ISSUE THREAD

**Issue by moMamdouhSaad** [ericferreira1992/slider-carousel#30]
hello guys,
i got a weird problem
is that the slider is disappear suddenly ( look for the attached video )

https://user-images.githubusercontent.com/55959564/104845813-0ed9b780-58e0-11eb-9a9e-9138babce2db.mp4

**Comment by ericferreira1992** [comment]
Hey @moMamdouhSaad. Thanks for the feedback. Problems like this have never been reported before. I did some changes, but the logical ideas are still the same. Update slider-carousel to 1.1.1 version and see the problem has been fixed.
